### ISSUE TITLE
Compilation error (undefined reference)

### ISSUE THREAD

**Issue by amirulmenjeni** [ros-melodic-arch/ros-melodic-turtle-actionlib#1] opened 2019-12-01 23:00 UTC
While updating this package I encountered a compilation error.

```
[ 91%] Built target geometry_msgs_generate_messages_cpp
Scanning dependencies of target shape_client
[ 93%] Building CXX object CMakeFiles/shape_client.dir/src/shape_client.cpp.o
[ 95%] Linking CXX executable devel/lib/turtle_actionlib/shape_client
/usr/bin/ld: CMakeFiles/shape_client.dir/src/shape_client.cpp.o: undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/shape_client.dir/build.make:101: devel/lib/turtle_actionlib/shape_client] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: CMakeFiles/shape_client.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ros-melodic-turtle-actionlib

```

The suggestion in https://github.com/facebook/Surround360/issues/3 works for me. I passed `"-pthread"` to `CMAKE_CXX_FLAGS`.

PKGBUILD patch: https://gist.github.com/amirulmenjeni/cff3e21bb07bf1d7fa7e18969c4f1ceb

**Comment by acxz** [comment] 2019-12-03 05:23
@jwhendy if you have time, can you attempt to reproduce this error, I have not been able to do so.

**Comment by acxz** [comment] 2019-12-10 19:54
Since no one besides you can produce this error, I am going to close this issue.

**Closed as completed by acxz** 2019-12-10 19:54 UTC
Labels: build error
